//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeWindowsForms.HyggeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HyggeService.HyggeServiceSoap")]
    public interface HyggeServiceSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchPoem", ReplyAction="*")]
        HyggeWindowsForms.HyggeService.FetchPoemResponse FetchPoem(HyggeWindowsForms.HyggeService.FetchPoemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FetchPoem", ReplyAction="*")]
        System.IAsyncResult BeginFetchPoem(HyggeWindowsForms.HyggeService.FetchPoemRequest request, System.AsyncCallback callback, object asyncState);
        
        HyggeWindowsForms.HyggeService.FetchPoemResponse EndFetchPoem(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchPoemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchPoem", Namespace="http://tempuri.org/", Order=0)]
        public HyggeWindowsForms.HyggeService.FetchPoemRequestBody Body;
        
        public FetchPoemRequest() {
        }
        
        public FetchPoemRequest(HyggeWindowsForms.HyggeService.FetchPoemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchPoemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public FetchPoemRequestBody() {
        }
        
        public FetchPoemRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchPoemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchPoemResponse", Namespace="http://tempuri.org/", Order=0)]
        public HyggeWindowsForms.HyggeService.FetchPoemResponseBody Body;
        
        public FetchPoemResponse() {
        }
        
        public FetchPoemResponse(HyggeWindowsForms.HyggeService.FetchPoemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchPoemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FetchPoemResult;
        
        public FetchPoemResponseBody() {
        }
        
        public FetchPoemResponseBody(string FetchPoemResult) {
            this.FetchPoemResult = FetchPoemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HyggeServiceSoapChannel : HyggeWindowsForms.HyggeService.HyggeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FetchPoemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FetchPoemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HyggeServiceSoapClient : System.ServiceModel.ClientBase<HyggeWindowsForms.HyggeService.HyggeServiceSoap>, HyggeWindowsForms.HyggeService.HyggeServiceSoap {
        
        private BeginOperationDelegate onBeginFetchPoemDelegate;
        
        private EndOperationDelegate onEndFetchPoemDelegate;
        
        private System.Threading.SendOrPostCallback onFetchPoemCompletedDelegate;
        
        public HyggeServiceSoapClient() {
        }
        
        public HyggeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HyggeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HyggeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HyggeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<FetchPoemCompletedEventArgs> FetchPoemCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HyggeWindowsForms.HyggeService.FetchPoemResponse HyggeWindowsForms.HyggeService.HyggeServiceSoap.FetchPoem(HyggeWindowsForms.HyggeService.FetchPoemRequest request) {
            return base.Channel.FetchPoem(request);
        }
        
        public string FetchPoem(string fileName) {
            HyggeWindowsForms.HyggeService.FetchPoemRequest inValue = new HyggeWindowsForms.HyggeService.FetchPoemRequest();
            inValue.Body = new HyggeWindowsForms.HyggeService.FetchPoemRequestBody();
            inValue.Body.fileName = fileName;
            HyggeWindowsForms.HyggeService.FetchPoemResponse retVal = ((HyggeWindowsForms.HyggeService.HyggeServiceSoap)(this)).FetchPoem(inValue);
            return retVal.Body.FetchPoemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HyggeWindowsForms.HyggeService.HyggeServiceSoap.BeginFetchPoem(HyggeWindowsForms.HyggeService.FetchPoemRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFetchPoem(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFetchPoem(string fileName, System.AsyncCallback callback, object asyncState) {
            HyggeWindowsForms.HyggeService.FetchPoemRequest inValue = new HyggeWindowsForms.HyggeService.FetchPoemRequest();
            inValue.Body = new HyggeWindowsForms.HyggeService.FetchPoemRequestBody();
            inValue.Body.fileName = fileName;
            return ((HyggeWindowsForms.HyggeService.HyggeServiceSoap)(this)).BeginFetchPoem(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HyggeWindowsForms.HyggeService.FetchPoemResponse HyggeWindowsForms.HyggeService.HyggeServiceSoap.EndFetchPoem(System.IAsyncResult result) {
            return base.Channel.EndFetchPoem(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndFetchPoem(System.IAsyncResult result) {
            HyggeWindowsForms.HyggeService.FetchPoemResponse retVal = ((HyggeWindowsForms.HyggeService.HyggeServiceSoap)(this)).EndFetchPoem(result);
            return retVal.Body.FetchPoemResult;
        }
        
        private System.IAsyncResult OnBeginFetchPoem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileName = ((string)(inValues[0]));
            return this.BeginFetchPoem(fileName, callback, asyncState);
        }
        
        private object[] OnEndFetchPoem(System.IAsyncResult result) {
            string retVal = this.EndFetchPoem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFetchPoemCompleted(object state) {
            if ((this.FetchPoemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FetchPoemCompleted(this, new FetchPoemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FetchPoemAsync(string fileName) {
            this.FetchPoemAsync(fileName, null);
        }
        
        public void FetchPoemAsync(string fileName, object userState) {
            if ((this.onBeginFetchPoemDelegate == null)) {
                this.onBeginFetchPoemDelegate = new BeginOperationDelegate(this.OnBeginFetchPoem);
            }
            if ((this.onEndFetchPoemDelegate == null)) {
                this.onEndFetchPoemDelegate = new EndOperationDelegate(this.OnEndFetchPoem);
            }
            if ((this.onFetchPoemCompletedDelegate == null)) {
                this.onFetchPoemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFetchPoemCompleted);
            }
            base.InvokeAsync(this.onBeginFetchPoemDelegate, new object[] {
                        fileName}, this.onEndFetchPoemDelegate, this.onFetchPoemCompletedDelegate, userState);
        }
    }
}
