//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="HyggeServiceSoap", Namespace="http://tempuri.org/")]
public partial class HyggeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback FetchPoemOperationCompleted;
    
    /// <remarks/>
    public HyggeService() {
        this.Url = "http://localhost/HyggeWS/HyggeService.asmx";
    }
    
    /// <remarks/>
    public event FetchPoemCompletedEventHandler FetchPoemCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchPoem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string FetchPoem(string fileName) {
        object[] results = this.Invoke("FetchPoem", new object[] {
                    fileName});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFetchPoem(string fileName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FetchPoem", new object[] {
                    fileName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndFetchPoem(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void FetchPoemAsync(string fileName) {
        this.FetchPoemAsync(fileName, null);
    }
    
    /// <remarks/>
    public void FetchPoemAsync(string fileName, object userState) {
        if ((this.FetchPoemOperationCompleted == null)) {
            this.FetchPoemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchPoemOperationCompleted);
        }
        this.InvokeAsync("FetchPoem", new object[] {
                    fileName}, this.FetchPoemOperationCompleted, userState);
    }
    
    private void OnFetchPoemOperationCompleted(object arg) {
        if ((this.FetchPoemCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FetchPoemCompleted(this, new FetchPoemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void FetchPoemCompletedEventHandler(object sender, FetchPoemCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FetchPoemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal FetchPoemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
